[package]
name = "block_chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.29"
num_cpus = "1.16.0"
rand = "0.8.5"
sha = "1.0.3"
sha256 = "1.4.0"
substring = "1.4.5"
